import json

nb = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Notebook 06: Comprehensive Model Comparison (All 3 Principal Components)\n",
    "\n",
    "In this notebook, we extend our evaluation to all three independent Principal Components generated by PCA on the subjective Likert ratings. Because PCA guarantees orthogonality, the 3 Principal Components representing Valence (Happiness/Positivity), Energy (Arousal), and Tension are predicted using strictly independent models."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import glob\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.impute import KNNImputer\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.linear_model import Lasso\n",
    "from sklearn.ensemble import RandomForestRegressor\n",
    "from xgboost import XGBRegressor\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load features\n",
    "base_path = os.path.abspath(os.path.join(os.getcwd(), '..')) if os.path.split(os.getcwd())[-1] == 'notebooks' else os.getcwd()\n",
    "features_dir = os.path.join(base_path, 'data', 'features')\n",
    "csv_files = glob.glob(os.path.join(features_dir, 'sub-*_features.csv'))\n",
    "full_df = pd.concat([pd.read_csv(f) for f in csv_files], ignore_index=True)\n",
    "\n",
    "# Impute missing Likert ratings and apply 3-component PCA\n",
    "q_cols = [f'Q{q}' for q in range(800, 808)]\n",
    "imputer = KNNImputer(n_neighbors=5, weights='distance')\n",
    "imputed_ratings = imputer.fit_transform(full_df[q_cols])\n",
    "\n",
    "pca = PCA(n_components=3)\n",
    "target_b_pca = pca.fit_transform(imputed_ratings)\n",
    "full_df['PC1_Valence_Subj'] = target_b_pca[:, 0]\n",
    "full_df['PC2_Energy_Subj'] = target_b_pca[:, 1]\n",
    "full_df['PC3_Tension_Subj'] = target_b_pca[:, 2]\n",
    "\n",
    "# Isolate features\n",
    "drop_cols = ['track_id', 'run', 'subject'] + q_cols + \\\n",
    "            ['number', 'valence', 'energy', 'tension', 'anger', 'fear', 'happy', 'sad', 'tender', 'TARGET'] + \\\n",
    "            ['PC1_Valence_Subj', 'PC2_Energy_Subj', 'PC3_Tension_Subj']\n",
    "drop_cols = [c for c in drop_cols if c in full_df.columns]\n",
    "X = full_df.drop(columns=drop_cols)\n",
    "subjects = full_df['subject'].unique()\n",
    "print(f\"Feature matrix shape (X): {X.shape}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "models = {\n",
    "    'Lasso (Linear)': Lasso(alpha=0.1, random_state=42, max_iter=10000),\n",
    "    'Random Forest (Bagged)': RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1),\n",
    "    'XGBoost (Boosting)': XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42, n_jobs=-1)\n",
    "}\n",
    "targets = ['PC1_Valence_Subj', 'PC2_Energy_Subj', 'PC3_Tension_Subj']\n",
    "results_table = []\n",
    "\n",
    "for pc in targets:\n",
    "    row = {'Response PCs': pc}\n",
    "    for model_name, model in models.items():\n",
    "        actuals = []\n",
    "        predictions = []\n",
    "        for test_sub in subjects:\n",
    "            train_idx = full_df['subject'] != test_sub\n",
    "            test_idx = full_df['subject'] == test_sub\n",
    "            X_train, y_train = X[train_idx], full_df.loc[train_idx, pc]\n",
    "            X_test, y_test = X[test_idx], full_df.loc[test_idx, pc]\n",
    "            \n",
    "            if 'Lasso' in model_name:\n",
    "                scaler = StandardScaler()\n",
    "                X_train_final = scaler.fit_transform(X_train)\n",
    "                X_test_final = scaler.transform(X_test)\n",
    "            else:\n",
    "                X_train_final, X_test_final = X_train.values, X_test.values\n",
    "            \n",
    "            model.fit(X_train_final, y_train)\n",
    "            preds = model.predict(X_test_final)\n",
    "            predictions.extend(preds)\n",
    "            actuals.extend(y_test)\n",
    "        \n",
    "        corr = np.corrcoef(actuals, predictions)[0,1]\n",
    "        row[model_name] = f\"{corr:.4f}\"\n",
    "    results_table.append(row)\n",
    "\n",
    "df_results = pd.DataFrame(results_table)\n",
    "display(df_results)"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

with open('notebooks/06_evaluate_all_pcs.ipynb', 'w') as f:
    json.dump(nb, f, indent=1)
